'\" t
.\"     Title: skyped
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 123
.\"    Manual: BitlBee manual
.\"    Source: BitlBee
.\"  Language: English
.\"
.TH "SKYPED" "1" "123" "BitlBee" "BitlBee manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
skyped \- allows remote control of the Skype GUI client
.SH "SYNOPSIS"
.sp
skyped [<options>]
.SH "DESCRIPTION"
.sp
Skype supports remote control of the GUI client only via X11 or DBus messages\&. This is hard in case you want remote control\&. This daemon listens on a TCP port and runs on the same machine where the GUI client runs\&. It passes all the input it gets to Skype directly, except for a few commands which is related to authentication\&. The whole communication is done via SSL\&.
.SH "CONFIGURATION"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Set up
~/\&.skyped/skyped\&.conf: Create the
~/\&.skyped
directory, copy
skyped\&.conf
and
skyped\&.cnf
from
/usr/local/etc/skyped/
to
~/\&.skyped, adjust
username
and
password\&. The
username
should be your Skype login and the
password
can be whatever you want, but you will have to specify that one when adding the Skype account to BitlBee (see later)\&.
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.sp
Here, and later \- /usr/local/etc can be different on your installation if you used the \-\-sysconfdir switch when running the configure of BitlBee\&.
.sp .5v
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Generate the SSL pem files:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
$ cd ~/\&.skyped
$ openssl req \-new \-x509 \-days 365 \-nodes \-config skyped\&.cnf \-out skyped\&.cert\&.pem \e
        \-keyout skyped\&.key\&.pem
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Start
skyped
(the TCP server), initially without detaching and enabling debug messages:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
$ skyped \-d \-n
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Start your
IRC
client, connect to BitlBee and add your account:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
account add skype <user> <pass>
.fi
.if n \{\
.RE
.\}
.sp
<user> should be your Skype account name, <pass> should be the one you declared in skyped\&.conf\&.
.SH "OPTIONS"
.PP
\-c, \-\-config
.RS 4
Path to configuration file (default: $HOME/\&.skyped/skyped\&.conf)
.RE
.PP
\-d, \-\-debug
.RS 4
Enable debug messages
.RE
.PP
\-h, \-\-help
.RS 4
Show short summary of options
.RE
.PP
\-H, \-\-host
.RS 4
Set the tcp host (default: 0\&.0\&.0\&.0)
.RE
.PP
\-l, \-\-log
.RS 4
Set the log file in background mode (default: none)
.RE
.PP
\-m, \-\-mock=<file>
.RS 4
Mock mode: replay session from file, instead of connecting to Skype\&.
.RE
.PP
\-n, \-\-nofork
.RS 4
Don\(cqt run as daemon in the background
.RE
.PP
\-s, \-\-dont\-start\-skype
.RS 4
Assume that skype is running independently, don\(cqt try to start/stop it\&.
.RE
.PP
\-p, \-\-port
.RS 4
Set the tcp port (default: 2727)
.RE
.PP
\-v, \-\-version
.RS 4
Display version information
.RE
.SH "AUTHOR"
.sp
Written by Miklos Vajna <vmiklos@vmiklos\&.hu>
