.\" Manual page for bitlbee.conf, derived from the modules.conf manpage.
.\" Writing a complete manpage from scratch is just too much work...
.\"
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the base distribution directory
.\"
.TH BITLBEE.CONF 5 "07 March 2004"
.UC 4
.SH NAME
bitlbee.conf \- configuration file for
.BR bitlbee (8)
.SH DESCRIPTION
This file contains system-wide settings for the
.BR bitlbee (8)
program. For more information about the file syntax, please read the
example configuration file which comes with the program. The default
file contains lots of comments which explain all the available options.
.SH SEE ALSO
.BR bitlbee (8)
