name: Tests

on:
  - push
  - pull_request

env:
  PKG_CONFIG_PATH: $HOME/otr/usr/lib/pkgconfig/
  LD_LIBRARY_PATH: $HOME/otr/usr/lib/

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
       sudo apt-get update && sudo apt-get -y install \
           libevent-dev \
           libpurple-dev \
           check \
           libpam0g-dev \
           libldap2-dev \
           fakeroot \
           debhelper \
           devscripts \
           libotr5-dev \
           libgnutls28-dev \
           libjsonparser-dev
    - name: Configure
      run: ./configure --pam=1 --ldap=1
    - name: Run testsuite
      run: make check
    - name: Build debian package
      run: dpkg-buildpackage -uc -us -b
